project:
  type: book
  output-dir: _book

book:
  title: "GeoCroissant Recipes"
  author:
    - "Croissant & GeoCroissant Working Group"
    - "croissant@mlcommons.org"
    - "croissant-geo@mlcommons.org"
  date: "Jan 20, 2026"
  search: true
  repo-url: https://github.com/ieee-grss-veda/veda-dcai
  page-navigation: true
  sidebar:
   search: true
   logo: "asset/GeoCroissant.jpg"
  page-footer:
    left: "GeoCroissant Recipes | [Vocabulary Portal](vdf/index.html)"
    center: "License: CC BY-ND 4.0"
    right:
      - icon: github
        href: https://github.com/ieee-grss-veda/veda-dcai

  chapters:
    - index.qmd
    - part: "**Introduction**"
      chapters:
        - text: "Overview of GeoCroissant"
          file: geocroissant_overview.md
        - text: "Introduction to GeoCroissant"
          file: "Introduction_to_GeoCroissant/Introduction_to_GeoCroissant.ipynb"
    - part: "**Specification**"
      chapters:
        - text: "Background & Motivation"
          file: spec-background.qmd
        - text: "Property Reference"
          file: spec-properties.qmd
        - text: "Use Cases"
          file: spec-usecases.qmd
        - text: "Appendices"
          file: spec-appendix.qmd
    - part: "**Catalog to GeoCroissant**"
      chapters:
        - text: "STAC to GeoCroissant"
          file: "STAC_to_GeoCroissant/stac_to_geocroissant.ipynb"
        - text: "NASA UMM-G to GeoCroissant"
          file: "NASA_UMM_to_GeoCroissant/NASA_UMM_G_to_GeoCroissant.ipynb"
        - text: "CEDA CMIP6 to GeoCroissant"
          file: "CEDA_UK_to_GeoCroissant_Support/CEDA_CMIP6_to_GeoCroissant.ipynb"
        - text: "Google Earth Engine to GeoCroissant"
          file: "GEE_to_GeoCroissant/GEE_to_GeoCroissant.ipynb"
    - part: "**Data Format to GeoCroissant**"
      chapters:
        - text: "GeoParquet to GeoCroissant"
          file: "GeoParquet_to_GeoCroissant_Support/GeoParquet_to_GeoCroissant.ipynb"
        - text: "HDF5 to GeoCroissant"
          file: "HDF5_Support_GeoCroissant/HDF5_to_GeoCroissant.ipynb"
        - text: "NetCDF to GeoCroissant"
          file: "SDO_to_GeoCroissant_NetCDF/SDO-Geocroissant_NetCDF.ipynb"
        - text: "Zarr Datacube to GeoCroissant"
          file: "Zarr_Datacube_to_GeoCroissant/Zarr_Datacube_to_GeoCroissant.ipynb"
    - part: "**GeoCroissant Extensions**"
      chapters:
        - text: "Time-Series Support"
          file: "GeoCroissant_Time_Series_Support/geocr_time-series.ipynb"
        - text: "OGC-TDML to GeoCroissant"
          file: "OGC_TDML_to_GeoCroissant_Support/ogc_tdml_to_geocr/ogc_tdml_to_geocr_conversion.ipynb"
        - text: "GeoCroissant to OGC-TDML"
          file: "OGC_TDML_to_GeoCroissant_Support/geocr_to_ogc_tdml/geocr_to_ogc_tdml_conversion.ipynb"
    - part: "**GeoCroissant to Standards**"
      chapters:
        - text: "GeoCroissant to STAC"
          file: "GeoCroissant_to_STAC/conversion-notebook.ipynb"
        - text: "GeoCroissant to GeoDCAT"
          file: "GeoCroissant_to_GeoDCAT/conversion-geodcat-notebook.ipynb"
    - references.qmd
    
execute:
  eval: false
  enabled: false
  timeout: 300
  error: false
  warning: false
  echo: true
  output: true
  freeze: false
  cache: false
  
format:
  html:
    number-sections: false
    theme:
      - cosmo
    css: custom.css
    code-tools: false
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    highlight-style: github
    code-overflow: wrap
    df-print: paged